--Project Euler #2
--Each new term in the Fibonacci sequence is generated by adding the previous
--two terms. By start with 1 and 2, the first 10 terms will be:
--1,2,3,5,8,13,21,34,55,89
--By considering the terms in the Fibonacci sequence whose values do not exceed
--four million, find the sum of the even-valued terms.

with Ada.Text_IO; use Ada.Text_IO;

procedure Euler2 is
  package IO renames Ada.Text_IO;

  --Variable declarations
  answer : Integer := 0;
  next : integer;
  first : Integer := 0;
  second : Integer := 1;
  
begin

  --Generate the Fibonacci sequence
  for i in Integer range 0 .. 100 loop
    if i <= 1 then
      next := i;
    else
      next := first + second;
      first := second;
      second := next;
    end if;
    
    if next > 4000000 then
      goto Break_Loop;
    end if;
    
    if next mod 2 = 0 then
      answer := answer + next;
    end if;
    
  end loop;
  
<<Break_Loop>>

  IO.Put_Line("The answer is: " & Integer'Image(answer));
  
end Euler2;